name: myback
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf_router: ^1.1.1

dev_dependencies:
  pedantic: ^1.10.0
